spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: books

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring082022.homework08.mongock

