spring:
  datasource:
    url: jdbc:h2:mem:bookdb

  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    contexts: main
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: true
